
# http://www.codewars.com/kata/54c9fcad28ec4c6e680011aa/train/python

def is_merge(s, part1, part2):

    if part1 == '':
        return s == part2
    if part2 == '':
        return s == part1
    if s == '':
        return part1 == part2 == ''

    char = s[0]
    if char not in (part1[0], part2[0]):
        return False
    elif char == part1[0] == part2[0]:
        new_s = s[1:]
        next_occurence = new_s.find(part1[0])
        new_s = new_s[:next_occurence] + new_s[next_occurence+1:]
        return is_merge(new_s, part1[1:], part2[1:])

    elif char == part1[0]:
        print '>>>, ', (s[1:], part1[1:], part2)
        return is_merge(s[1:], part1[1:], part2)
    else:
        print '>>>, ', (s[1:], part1, part2[1:])
        return is_merge(s[1:], part1, part2[1:])


# print is_merge('codewars', 'code', 'wars')
# print is_merge('codewars', 'cdw', 'oears')
# print not is_merge('codewars', 'cod', 'wars')

# print is_merge('wars', 'w', 'ars')
# print is_merge('ewars', 'w', 'ears')



# def is_merge(s, part1, part2):
#     # print s
#     # print part1
#     # print part2

#     if part1 == '':
#         return s == part2
#     if part2 == '':
#         return s == part1
#     if s == '':
#         return part1 == part2 == ''

#     char = s[-1]
#     if char not in (part1[-1], part2[-1]):
#         return False
#     elif char == part1[-1]:
#         print '>>>', (s[:-1], part1[:-1], part2)
#         return is_merge(s[:-1], part1[:-1], part2)
#     else:
#         print '>>>', (s[:-1], part1, part2[:-1])
#         return is_merge(s[:-1], part1, part2[:-1])
a = 'Can we merge it? Yes, we can!'
b = 'nw mege eea'
c = 'Ca er it?Ys, w cn!'

total = 'Bananas from Bahamas'
left = 'Bahas'
right = 'Bananas from am'


print is_merge(total, left, right)



# testcase:


# is_merge
# can handle some basic cases
# >>>, ('odewars', 'ode', 'wars')
# >>>, ('dewars', 'de', 'wars')
# >>>, ('ewars', 'e', 'wars')
# >>>, ('wars', '', 'wars')
# Test Passed
# >>>, ('odewars', 'dwr', 'oeas')
# >>>, ('dewars', 'dwr', 'eas')
# >>>, ('ewars', 'wr', 'eas')
# >>>, ('wars', 'wr', 'as')
# >>>, ('ars', 'r', 'as')
# >>>, ('rs', 'r', 's')
# >>>, ('s', '', 's')
# Test Passed
# >>>, ('aking progress', 'ak pross', 'inggre')
# >>>, ('king progress', 'k pross', 'inggre')
# >>>, ('ing progress', ' pross', 'inggre')
# >>>, ('ng progress', ' pross', 'nggre')
# >>>, ('g progress', ' pross', 'ggre')
# >>>, (' progress', ' pross', 'gre')
# >>>, ('progress', 'pross', 'gre')
# >>>, ('rogress', 'ross', 'gre')
# >>>, ('ogress', 'oss', 'gre')
# >>>, ('gress', 'ss', 'gre')
# >>>, ('ress', 'ss', 're')
# >>>, ('ess', 'ss', 'e')
# >>>, ('ss', 'ss', '')
# Test Passed
# Test Passed
# Test Passed
# can handle empty parts
# Test Passed
# Test Passed
# Test Passed
# Test Passed
# can handle too few characters
# Test Passed
# Test Passed
# can handle extra characters
# Test Passed
# Test Passed
# can handle characters in wrong order
# >>>, ('odewars', 'ode', 'wasr')
# >>>, ('dewars', 'de', 'wasr')
# >>>, ('ewars', 'e', 'wasr')
# >>>, ('wars', '', 'wasr')
# Test Passed
# >>>, ('odewars', 'wdr', 'oeas')
# >>>, ('dewars', 'wdr', 'eas')
# Test Passed
# can handle bananas
# >>>, ('nas from ahamas', 'has', 'anas from am')
# Bananas from Bahamas
# can handle some random cases
# >>>, ("an we merge it? No, we can't", 'nwmeet Yes,can!', 'a e rg i? we ')
# >>>, ("n we merge it? No, we can't", 'nwmeet Yes,can!', ' e rg i? we ')
# >>>, (" we merge it? No, we can't", 'wmeet Yes,can!', ' e rg i? we ')
# >>>, ("we merge it? No, we can't", 'wmeet Yes,can!', 'e rg i? we ')
# >>>, ("e merge it? No, we can't", 'meet Yes,can!', 'e rg i? we ')
# >>>, (" merge it? No, we can't", 'meet Yes,can!', ' rg i? we ')
# >>>, ("merge it? No, we can't", 'meet Yes,can!', 'rg i? we ')
# >>>, ("erge it? No, we can't", 'eet Yes,can!', 'rg i? we ')
# >>>, ("rge it? No, we can't", 'et Yes,can!', 'rg i? we ')
# >>>, ("ge it? No, we can't", 'et Yes,can!', 'g i? we ')
# >>>, ("e it? No, we can't", 'et Yes,can!', ' i? we ')
# >>>, (" it? No, we can't", 't Yes,can!', ' i? we ')
# >>>, ("it? No, we can't", 't Yes,can!', 'i? we ')
# >>>, ("t? No, we can't", 't Yes,can!', '? we ')
# >>>, ("? No, we can't", ' Yes,can!', '? we ')
# >>>, (" No, we can't", ' Yes,can!', ' we ')
# Test Passed
# >>>, ('an we merge it? Yes, we can!', ' eerge t?e we a', 'anw mi Ys,cn!')
# >>>, ('n we merge it? Yes, we can!', ' eerge t?e we a', 'nw mi Ys,cn!')
# >>>, (' we merge it? Yes, we can!', ' eerge t?e we a', 'w mi Ys,cn!')
# >>>, ('we merge it? Yes, we can!', 'eerge t?e we a', 'w mi Ys,cn!')
# >>>, ('e merge it? Yes, we can!', 'eerge t?e we a', ' mi Ys,cn!')
# >>>, (' merge it? Yes, we can!', 'erge t?e we a', ' mi Ys,cn!')
# >>>, ('merge it? Yes, we can!', 'erge t?e we a', 'mi Ys,cn!')
# >>>, ('erge it? Yes, we can!', 'erge t?e we a', 'i Ys,cn!')
# >>>, ('rge it? Yes, we can!', 'rge t?e we a', 'i Ys,cn!')
# >>>, ('ge it? Yes, we can!', 'ge t?e we a', 'i Ys,cn!')
# >>>, ('e it? Yes, we can!', 'e t?e we a', 'i Ys,cn!')
# >>>, (' it? Yes, we can!', ' t?e we a', 'i Ys,cn!')
# >>>, ('it? Yes, we can!', 't?e we a', 'i Ys,cn!')
# >>>, ('t? Yes, we can!', 't?e we a', ' Ys,cn!')
# >>>, ('? Yes, we can!', '?e we a', ' Ys,cn!')
# >>>, (' Yes, we can!', 'e we a', ' Ys,cn!')
# >>>, ('Yes, we can!', 'e we a', 'Ys,cn!')
# >>>, ('es, we can!', 'e we a', 's,cn!')
# >>>, ('s, we can!', ' we a', 's,cn!')
# >>>, (', we can!', ' we a', ',cn!')
# >>>, (' we can!', ' we a', 'cn!')
# >>>, ('we can!', 'we a', 'cn!')
# >>>, ('e can!', 'e a', 'cn!')
# >>>, (' can!', ' a', 'cn!')
# >>>, ('can!', 'a', 'cn!')
# >>>, ('an!', 'a', 'n!')
# >>>, ('n!', '', 'n!')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'awer i? e, we ', 'n e mgetYscan!')
# >>>, ("n we merge it? No, we can't", 'wer i? e, we ', 'n e mgetYscan!')
# >>>, (" we merge it? No, we can't", 'wer i? e, we ', ' e mgetYscan!')
# >>>, ("we merge it? No, we can't", 'wer i? e, we ', 'e mgetYscan!')
# >>>, ("e merge it? No, we can't", 'er i? e, we ', 'e mgetYscan!')
# >>>, ("mrge it? No, we can't", 'r i? e, we ', 'mgetYscan!')
# >>>, ("rge it? No, we can't", 'r i? e, we ', 'getYscan!')
# >>>, ("ge it? No, we can't", ' i? e, we ', 'getYscan!')
# >>>, ("e it? No, we can't", ' i? e, we ', 'etYscan!')
# >>>, (" it? No, we can't", ' i? e, we ', 'tYscan!')
# >>>, ("it? No, we can't", 'i? e, we ', 'tYscan!')
# >>>, ("t? No, we can't", '? e, we ', 'tYscan!')
# >>>, ("? No, we can't", '? e, we ', 'Yscan!')
# >>>, (" No, we can't", ' e, we ', 'Yscan!')
# >>>, ("No, we can't", 'e, we ', 'Yscan!')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'ne ege itwe a', 'a wmr? Yes, cn!')
# >>>, ("n we merge it? No, we can't", 'ne ege itwe a', ' wmr? Yes, cn!')
# >>>, (" we merge it? No, we can't", 'e ege itwe a', ' wmr? Yes, cn!')
# >>>, ("we merge it? No, we can't", 'e ege itwe a', 'wmr? Yes, cn!')
# >>>, ("e merge it? No, we can't", 'e ege itwe a', 'mr? Yes, cn!')
# >>>, (" merge it? No, we can't", ' ege itwe a', 'mr? Yes, cn!')
# >>>, ("merge it? No, we can't", 'ege itwe a', 'mr? Yes, cn!')
# >>>, ("erge it? No, we can't", 'ege itwe a', 'r? Yes, cn!')
# >>>, ("rge it? No, we can't", 'ge itwe a', 'r? Yes, cn!')
# >>>, ("ge it? No, we can't", 'ge itwe a', '? Yes, cn!')
# >>>, ("e it? No, we can't", 'e itwe a', '? Yes, cn!')
# >>>, (" it? No, we can't", ' itwe a', '? Yes, cn!')
# >>>, ("it? No, we can't", 'itwe a', '? Yes, cn!')
# >>>, ("t? No, we can't", 'twe a', '? Yes, cn!')
# >>>, ("? No, we can't", 'we a', '? Yes, cn!')
# >>>, (" No, we can't", 'we a', ' Yes, cn!')
# >>>, ("No, we can't", 'we a', 'Yes, cn!')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'an wrgi es,wcn!', 'e mee t?Y e a')
# >>>, ("n we merge it? No, we can't", 'n wrgi es,wcn!', 'e mee t?Y e a')
# >>>, (" we merge it? No, we can't", ' wrgi es,wcn!', 'e mee t?Y e a')
# >>>, ("we merge it? No, we can't", 'wrgi es,wcn!', 'e mee t?Y e a')
# >>>, ("e merge it? No, we can't", 'rgi es,wcn!', 'e mee t?Y e a')
# >>>, (" merge it? No, we can't", 'rgi es,wcn!', ' mee t?Y e a')
# >>>, ("merge it? No, we can't", 'rgi es,wcn!', 'mee t?Y e a')
# >>>, ("erge it? No, we can't", 'rgi es,wcn!', 'ee t?Y e a')
# >>>, ("rge it? No, we can't", 'rgi es,wcn!', 'e t?Y e a')
# >>>, ("ge it? No, we can't", 'gi es,wcn!', 'e t?Y e a')
# >>>, ("e it? No, we can't", 'i es,wcn!', 'e t?Y e a')
# >>>, (" it? No, we can't", 'i es,wcn!', ' t?Y e a')
# >>>, ("it? No, we can't", 'i es,wcn!', 't?Y e a')
# >>>, ("t? No, we can't", ' es,wcn!', 't?Y e a')
# >>>, ("? No, we can't", ' es,wcn!', '?Y e a')
# >>>, (" No, we can't", ' es,wcn!', 'Y e a')
# >>>, ("No, we can't", 'es,wcn!', 'Y e a')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'anwemr ie can!', ' eget? Ys,we ')
# >>>, ("n we merge it? No, we can't", 'nwemr ie can!', ' eget? Ys,we ')
# >>>, (" we merge it? No, we can't", 'wemr ie can!', ' eget? Ys,we ')
# >>>, ("we merge it? No, we can't", 'wemr ie can!', ' eget? Ys,we ')
# >>>, ("e merge it? No, we can't", 'emr ie can!', ' eget? Ys,we ')
# >>>, (" merge it? No, we can't", 'mr ie can!', ' eget? Ys,we ')
# >>>, ("merge it? No, we can't", 'mr ie can!', 'eget? Ys,we ')
# >>>, ("erge it? No, we can't", 'r ie can!', 'eget? Ys,we ')
# >>>, ("rge it? No, we can't", 'r ie can!', 'get? Ys,we ')
# >>>, ("ge it? No, we can't", ' ie can!', 'get? Ys,we ')
# >>>, ("e it? No, we can't", ' ie can!', 'et? Ys,we ')
# >>>, (" it? No, we can't", ' ie can!', 't? Ys,we ')
# >>>, ("it? No, we can't", 'ie can!', 't? Ys,we ')
# >>>, ("t? No, we can't", 'e can!', 't? Ys,we ')
# >>>, ("? No, we can't", 'e can!', '? Ys,we ')
# >>>, (" No, we can't", 'e can!', ' Ys,we ')
# >>>, ("No, we can't", 'e can!', 'Ys,we ')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'an me t?Yes e an!', 'wergei ,wc')
# >>>, ("n we merge it? No, we can't", 'n me t?Yes e an!', 'wergei ,wc')
# >>>, (" we merge it? No, we can't", ' me t?Yes e an!', 'wergei ,wc')
# >>>, ("we merge it? No, we can't", ' me t?Yes e an!', 'wergei ,wc')
# >>>, ("e merge it? No, we can't", ' me t?Yes e an!', 'ergei ,wc')
# >>>, (" merge it? No, we can't", ' me t?Yes e an!', 'rgei ,wc')
# >>>, ("merge it? No, we can't", 'me t?Yes e an!', 'rgei ,wc')
# >>>, ("erge it? No, we can't", 'e t?Yes e an!', 'rgei ,wc')
# >>>, ("rge it? No, we can't", ' t?Yes e an!', 'rgei ,wc')
# >>>, ("ge it? No, we can't", ' t?Yes e an!', 'gei ,wc')
# >>>, ("e it? No, we can't", ' t?Yes e an!', 'ei ,wc')
# >>>, (" it? No, we can't", ' t?Yes e an!', 'i ,wc')
# >>>, ("it? No, we can't", 't?Yes e an!', 'i ,wc')
# >>>, ("t? No, we can't", 't?Yes e an!', ' ,wc')
# >>>, ("? No, we can't", '?Yes e an!', ' ,wc')
# >>>, (" No, we can't", 'Yes e an!', ' ,wc')
# >>>, ("No, we can't", 'Yes e an!', ',wc')
# Test Passed
# >>>, ("an we merge it? No, we can't", ' e reit? e can', 'anwmeg Yes, w!')
# >>>, ("n we merge it? No, we can't", ' e reit? e can', 'nwmeg Yes, w!')
# >>>, (" we merge it? No, we can't", ' e reit? e can', 'wmeg Yes, w!')
# >>>, ("we merge it? No, we can't", 'e reit? e can', 'wmeg Yes, w!')
# >>>, ("e merge it? No, we can't", 'e reit? e can', 'meg Yes, w!')
# >>>, (" merge it? No, we can't", ' reit? e can', 'meg Yes, w!')
# >>>, ("merge it? No, we can't", 'reit? e can', 'meg Yes, w!')
# >>>, ("erge it? No, we can't", 'reit? e can', 'eg Yes, w!')
# >>>, ("rge it? No, we can't", 'reit? e can', 'g Yes, w!')
# >>>, ("ge it? No, we can't", 'eit? e can', 'g Yes, w!')
# >>>, ("e it? No, we can't", 'eit? e can', ' Yes, w!')
# >>>, (" it? No, we can't", 'it? e can', ' Yes, w!')
# >>>, ("it? No, we can't", 'it? e can', 'Yes, w!')
# >>>, ("t? No, we can't", 't? e can', 'Yes, w!')
# >>>, ("? No, we can't", '? e can', 'Yes, w!')
# >>>, (" No, we can't", ' e can', 'Yes, w!')
# >>>, ("No, we can't", 'e can', 'Yes, w!')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'an et Ye w an', 'we mrge i?s,ec!')
# >>>, ("n we merge it? No, we can't", 'n et Ye w an', 'we mrge i?s,ec!')
# >>>, (" we merge it? No, we can't", ' et Ye w an', 'we mrge i?s,ec!')
# >>>, ("we merge it? No, we can't", 'et Ye w an', 'we mrge i?s,ec!')
# >>>, ("e merge it? No, we can't", 'et Ye w an', 'e mrge i?s,ec!')
# >>>, ("mrge it? No, we can't", 't Ye w an', 'mrge i?s,ec!')
# >>>, ("rge it? No, we can't", 't Ye w an', 'rge i?s,ec!')
# >>>, ("ge it? No, we can't", 't Ye w an', 'ge i?s,ec!')
# >>>, ("e it? No, we can't", 't Ye w an', 'e i?s,ec!')
# >>>, (" it? No, we can't", 't Ye w an', ' i?s,ec!')
# >>>, ("it? No, we can't", 't Ye w an', 'i?s,ec!')
# >>>, ("t? No, we can't", 't Ye w an', '?s,ec!')
# >>>, ("? No, we can't", ' Ye w an', '?s,ec!')
# >>>, (" No, we can't", ' Ye w an', 's,ec!')
# >>>, ("No, we can't", 'Ye w an', 's,ec!')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'an erge it Yeswec!', 'w me?, an')
# >>>, ("n we merge it? No, we can't", 'n erge it Yeswec!', 'w me?, an')
# >>>, (" we merge it? No, we can't", ' erge it Yeswec!', 'w me?, an')
# >>>, ("we merge it? No, we can't", 'erge it Yeswec!', 'w me?, an')
# >>>, ("e merge it? No, we can't", 'erge it Yeswec!', ' me?, an')
# >>>, (" merge it? No, we can't", 'rge it Yeswec!', ' me?, an')
# >>>, ("merge it? No, we can't", 'rge it Yeswec!', 'me?, an')
# >>>, ("erge it? No, we can't", 'rge it Yeswec!', 'e?, an')
# >>>, ("rge it? No, we can't", 'rge it Yeswec!', '?, an')
# >>>, ("ge it? No, we can't", 'ge it Yeswec!', '?, an')
# >>>, ("e it? No, we can't", 'e it Yeswec!', '?, an')
# >>>, (" it? No, we can't", ' it Yeswec!', '?, an')
# >>>, ("it? No, we can't", 'it Yeswec!', '?, an')
# >>>, ("t? No, we can't", 't Yeswec!', '?, an')
# >>>, ("? No, we can't", ' Yeswec!', '?, an')
# >>>, (" No, we can't", ' Yeswec!', ', an')
# >>>, ("No, we can't", 'Yeswec!', ', an')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'ae egi Ye, e a!', 'n wmre t?swcn')
# >>>, ("n we merge it? No, we can't", 'e egi Ye, e a!', 'n wmre t?swcn')
# >>>, (" we merge it? No, we can't", 'e egi Ye, e a!', ' wmre t?swcn')
# >>>, ("we merge it? No, we can't", 'e egi Ye, e a!', 'wmre t?swcn')
# >>>, ("e merge it? No, we can't", 'e egi Ye, e a!', 'mre t?swcn')
# >>>, (" merge it? No, we can't", ' egi Ye, e a!', 'mre t?swcn')
# >>>, ("merge it? No, we can't", 'egi Ye, e a!', 'mre t?swcn')
# >>>, ("erge it? No, we can't", 'egi Ye, e a!', 're t?swcn')
# >>>, ("rge it? No, we can't", 'gi Ye, e a!', 're t?swcn')
# >>>, ("ge it? No, we can't", 'gi Ye, e a!', 'e t?swcn')
# >>>, ("e it? No, we can't", 'i Ye, e a!', 'e t?swcn')
# >>>, (" it? No, we can't", 'i Ye, e a!', ' t?swcn')
# >>>, ("it? No, we can't", 'i Ye, e a!', 't?swcn')
# >>>, ("t? No, we can't", ' Ye, e a!', 't?swcn')
# >>>, ("? No, we can't", ' Ye, e a!', '?swcn')
# >>>, (" No, we can't", ' Ye, e a!', 'swcn')
# >>>, ("No, we can't", 'Ye, e a!', 'swcn')
# Test Passed
# >>>, ('an we merge it? Yes, we can!', 'anwemere iY,we ca!', ' gt? es n')
# >>>, ('n we merge it? Yes, we can!', 'nwemere iY,we ca!', ' gt? es n')
# >>>, (' we merge it? Yes, we can!', 'wemere iY,we ca!', ' gt? es n')
# >>>, ('we merge it? Yes, we can!', 'wemere iY,we ca!', ' gt? es n')
# >>>, ('e merge it? Yes, we can!', 'emere iY,we ca!', ' gt? es n')
# >>>, (' merge it? Yes, we can!', 'mere iY,we ca!', ' gt? es n')
# >>>, ('merge it? Yes, we can!', 'mere iY,we ca!', 'gt? es n')
# >>>, ('erge it? Yes, we can!', 'ere iY,we ca!', 'gt? es n')
# >>>, ('rge it? Yes, we can!', 're iY,we ca!', 'gt? es n')
# >>>, ('ge it? Yes, we can!', 'e iY,we ca!', 'gt? es n')
# >>>, ('e it? Yes, we can!', 'e iY,we ca!', 't? es n')
# >>>, (' it? Yes, we can!', ' iY,we ca!', 't? es n')
# >>>, ('it? Yes, we can!', 'iY,we ca!', 't? es n')
# >>>, ('t? Yes, we can!', 'Y,we ca!', 't? es n')
# >>>, ('? Yes, we can!', 'Y,we ca!', '? es n')
# >>>, (' Yes, we can!', 'Y,we ca!', ' es n')
# >>>, ('Yes, we can!', 'Y,we ca!', 'es n')
# >>>, ('es, we can!', ',we ca!', 'es n')
# >>>, ('s, we can!', ',we ca!', 's n')
# >>>, (', we can!', ',we ca!', ' n')
# >>>, (' we can!', 'we ca!', ' n')
# >>>, ('we can!', 'we ca!', 'n')
# >>>, ('e can!', 'e ca!', 'n')
# >>>, (' can!', ' ca!', 'n')
# >>>, ('can!', 'ca!', 'n')
# >>>, ('an!', 'a!', 'n')
# >>>, ('n!', '!', 'n')
# >>>, ('!', '!', '')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'aeer i? Yswe an!', 'n w mgete, c')
# >>>, ("n we merge it? No, we can't", 'eer i? Yswe an!', 'n w mgete, c')
# >>>, (" we merge it? No, we can't", 'eer i? Yswe an!', ' w mgete, c')
# >>>, ("we merge it? No, we can't", 'eer i? Yswe an!', 'w mgete, c')
# >>>, ("e merge it? No, we can't", 'eer i? Yswe an!', ' mgete, c')
# >>>, (" merge it? No, we can't", 'er i? Yswe an!', ' mgete, c')
# >>>, ("merge it? No, we can't", 'er i? Yswe an!', 'mgete, c')
# >>>, ("erge it? No, we can't", 'er i? Yswe an!', 'gete, c')
# >>>, ("rge it? No, we can't", 'r i? Yswe an!', 'gete, c')
# >>>, ("ge it? No, we can't", ' i? Yswe an!', 'gete, c')
# >>>, ("e it? No, we can't", ' i? Yswe an!', 'ete, c')
# >>>, (" it? No, we can't", ' i? Yswe an!', 'te, c')
# >>>, ("it? No, we can't", 'i? Yswe an!', 'te, c')
# >>>, ("t? No, we can't", '? Yswe an!', 'te, c')
# >>>, ("? No, we can't", '? Yswe an!', 'e, c')
# >>>, (" No, we can't", ' Yswe an!', 'e, c')
# >>>, ("No, we can't", 'Yswe an!', 'e, c')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'a weeit?Y, an!', 'ne mrg eswe c')
# >>>, ("n we merge it? No, we can't", ' weeit?Y, an!', 'ne mrg eswe c')
# >>>, (" we merge it? No, we can't", ' weeit?Y, an!', 'e mrg eswe c')
# >>>, ("we merge it? No, we can't", 'weeit?Y, an!', 'e mrg eswe c')
# >>>, ("e merge it? No, we can't", 'eeit?Y, an!', 'e mrg eswe c')
# >>>, ("mrge it? No, we can't", 'eit?Y, an!', 'mrg eswe c')
# >>>, ("rge it? No, we can't", 'eit?Y, an!', 'rg eswe c')
# >>>, ("ge it? No, we can't", 'eit?Y, an!', 'g eswe c')
# >>>, ("e it? No, we can't", 'eit?Y, an!', ' eswe c')
# >>>, (" it? No, we can't", 'it?Y, an!', ' eswe c')
# >>>, ("it? No, we can't", 'it?Y, an!', ' eswe c')
# >>>, ("t? No, we can't", 't?Y, an!', ' eswe c')
# >>>, ("? No, we can't", '?Y, an!', ' eswe c')
# >>>, (" No, we can't", 'Y, an!', ' eswe c')
# >>>, ("No, we can't", 'Y, an!', 'eswe c')
# Test Passed
# >>>, ('an we merge it? Yes, we can!', 'n e mer itYwe cn', 'awge? es, a!')
# >>>, ('n we merge it? Yes, we can!', 'n e mer itYwe cn', 'wge? es, a!')
# >>>, (' we merge it? Yes, we can!', ' e mer itYwe cn', 'wge? es, a!')
# >>>, ('we merge it? Yes, we can!', 'e mer itYwe cn', 'wge? es, a!')
# >>>, ('e merge it? Yes, we can!', 'e mer itYwe cn', 'ge? es, a!')
# >>>, (' merge it? Yes, we can!', ' mer itYwe cn', 'ge? es, a!')
# >>>, ('merge it? Yes, we can!', 'mer itYwe cn', 'ge? es, a!')
# >>>, ('erge it? Yes, we can!', 'er itYwe cn', 'ge? es, a!')
# >>>, ('rge it? Yes, we can!', 'r itYwe cn', 'ge? es, a!')
# >>>, ('ge it? Yes, we can!', ' itYwe cn', 'ge? es, a!')
# >>>, ('e it? Yes, we can!', ' itYwe cn', 'e? es, a!')
# >>>, (' it? Yes, we can!', ' itYwe cn', '? es, a!')
# >>>, ('it? Yes, we can!', 'itYwe cn', '? es, a!')
# >>>, ('t? Yes, we can!', 'tYwe cn', '? es, a!')
# >>>, ('? Yes, we can!', 'Ywe cn', '? es, a!')
# >>>, (' Yes, we can!', 'Ywe cn', ' es, a!')
# >>>, ('Yes, we can!', 'Ywe cn', 'es, a!')
# >>>, ('es, we can!', 'we cn', 'es, a!')
# >>>, ('s, we can!', 'we cn', 's, a!')
# >>>, (', we can!', 'we cn', ', a!')
# >>>, (' we can!', 'we cn', ' a!')
# >>>, ('we can!', 'we cn', 'a!')
# >>>, ('e can!', 'e cn', 'a!')
# >>>, (' can!', ' cn', 'a!')
# >>>, ('can!', 'cn', 'a!')
# >>>, ('an!', 'n', 'a!')
# >>>, ('n!', 'n', '!')
# >>>, ('!', '', '!')
# Test Passed
# >>>, ('an we merge it? Yes, we can!', 'a ere?e,we can!', 'nwe mg it Ys ')
# >>>, ('n we merge it? Yes, we can!', ' ere?e,we can!', 'nwe mg it Ys ')
# >>>, (' we merge it? Yes, we can!', ' ere?e,we can!', 'we mg it Ys ')
# >>>, ('we merge it? Yes, we can!', 'ere?e,we can!', 'we mg it Ys ')
# >>>, ('e merge it? Yes, we can!', 'ere?e,we can!', 'e mg it Ys ')
# >>>, ('mrge it? Yes, we can!', 're?e,we can!', 'mg it Ys ')
# >>>, ('rge it? Yes, we can!', 're?e,we can!', 'g it Ys ')
# >>>, ('ge it? Yes, we can!', 'e?e,we can!', 'g it Ys ')
# >>>, ('e it? Yes, we can!', 'e?e,we can!', ' it Ys ')
# >>>, (' it? Yes, we can!', '?e,we can!', ' it Ys ')
# >>>, ('it? Yes, we can!', '?e,we can!', 'it Ys ')
# >>>, ('t? Yes, we can!', '?e,we can!', 't Ys ')
# >>>, ('? Yes, we can!', '?e,we can!', ' Ys ')
# >>>, (' Yes, we can!', 'e,we can!', ' Ys ')
# >>>, ('Yes, we can!', 'e,we can!', 'Ys ')
# >>>, ('es, we can!', 'e,we can!', 's ')
# >>>, ('s, we can!', ',we can!', 's ')
# >>>, (', we can!', ',we can!', ' ')
# >>>, (' we can!', 'we can!', ' ')
# >>>, ('we can!', 'we can!', '')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'anwmgeit? Y, e c', ' e er eswan!')
# >>>, ("n we merge it? No, we can't", 'nwmgeit? Y, e c', ' e er eswan!')
# >>>, (" we merge it? No, we can't", 'wmgeit? Y, e c', ' e er eswan!')
# >>>, ("we merge it? No, we can't", 'wmgeit? Y, e c', 'e er eswan!')
# >>>, ("e merge it? No, we can't", 'mgeit? Y, e c', 'e er eswan!')
# >>>, (" merge it? No, we can't", 'mgeit? Y, e c', ' er eswan!')
# >>>, ("merge it? No, we can't", 'mgeit? Y, e c', 'er eswan!')
# >>>, ("erge it? No, we can't", 'geit? Y, e c', 'er eswan!')
# >>>, ("rge it? No, we can't", 'geit? Y, e c', 'r eswan!')
# >>>, ("ge it? No, we can't", 'geit? Y, e c', ' eswan!')
# >>>, ("e it? No, we can't", 'eit? Y, e c', ' eswan!')
# >>>, (" it? No, we can't", 'it? Y, e c', ' eswan!')
# >>>, ("it? No, we can't", 'it? Y, e c', 'eswan!')
# >>>, ("t? No, we can't", 't? Y, e c', 'eswan!')
# >>>, ("? No, we can't", '? Y, e c', 'eswan!')
# >>>, (" No, we can't", ' Y, e c', 'eswan!')
# >>>, ("No, we can't", 'Y, e c', 'eswan!')
# Test Passed
# >>>, ("an we merge it? No, we can't", 'a emrgetYs n', 'nw e i? e, weca!')
# >>>, ("n we merge it? No, we can't", ' emrgetYs n', 'nw e i? e, weca!')
# >>>, (" we merge it? No, we can't", ' emrgetYs n', 'w e i? e, weca!')
# >>>, ("we merge it? No, we can't", 'emrgetYs n', 'w e i? e, weca!')
# >>>, ("e merge it? No, we can't", 'emrgetYs n', ' e i? e, weca!')
# >>>, (" merge it? No, we can't", 'mrgetYs n', ' e i? e, weca!')
# >>>, ("merge it? No, we can't", 'mrgetYs n', 'e i? e, weca!')
# >>>, ("erge it? No, we can't", 'rgetYs n', 'e i? e, weca!')
# >>>, ("rge it? No, we can't", 'rgetYs n', ' i? e, weca!')
# >>>, ("ge it? No, we can't", 'getYs n', ' i? e, weca!')
# >>>, ("e it? No, we can't", 'etYs n', ' i? e, weca!')
# >>>, (" it? No, we can't", 'tYs n', ' i? e, weca!')
# >>>, ("it? No, we can't", 'tYs n', 'i? e, weca!')
# >>>, ("t? No, we can't", 'tYs n', '? e, weca!')
# >>>, ("? No, we can't", 'Ys n', '? e, weca!')
# >>>, (" No, we can't", 'Ys n', ' e, weca!')
# >>>, ("No, we can't", 'Ys n', 'e, weca!')
# Test Passed
# >>>, ("an we merge it? No, we can't", ' eeeitYs w !', 'anw mrg ? e,ecan')
# >>>, ("n we merge it? No, we can't", ' eeeitYs w !', 'nw mrg ? e,ecan')
# >>>, (" we merge it? No, we can't", ' eeeitYs w !', 'w mrg ? e,ecan')
# >>>, ("we merge it? No, we can't", 'eeeitYs w !', 'w mrg ? e,ecan')
# >>>, ("e merge it? No, we can't", 'eeeitYs w !', ' mrg ? e,ecan')
# >>>, (" merge it? No, we can't", 'eeitYs w !', ' mrg ? e,ecan')
# >>>, ("merge it? No, we can't", 'eeitYs w !', 'mrg ? e,ecan')
# >>>, ("erge it? No, we can't", 'eeitYs w !', 'rg ? e,ecan')
# >>>, ("rge it? No, we can't", 'eitYs w !', 'rg ? e,ecan')
# >>>, ("ge it? No, we can't", 'eitYs w !', 'g ? e,ecan')
# >>>, ("e it? No, we can't", 'eitYs w !', ' ? e,ecan')
# >>>, (" it? No, we can't", 'itYs w !', ' ? e,ecan')
# >>>, ("it? No, we can't", 'itYs w !', '? e,ecan')
# >>>, ("t? No, we can't", 'tYs w !', '? e,ecan')
# >>>, ("? No, we can't", 'Ys w !', '? e,ecan')
# >>>, (" No, we can't", 'Ys w !', ' e,ecan')
# >>>, ("No, we can't", 'Ys w !', 'e,ecan')
# Test Passed
# >>>, ('an we merge it? Yes, we can!', 'an emg it?esw can!', 'w ere Y, e')
# >>>, ('n we merge it? Yes, we can!', 'n emg it?esw can!', 'w ere Y, e')
# >>>, (' we merge it? Yes, we can!', ' emg it?esw can!', 'w ere Y, e')
# >>>, ('we merge it? Yes, we can!', 'emg it?esw can!', 'w ere Y, e')
# >>>, ('e merge it? Yes, we can!', 'emg it?esw can!', ' ere Y, e')
# >>>, (' merge it? Yes, we can!', 'mg it?esw can!', ' ere Y, e')
# >>>, ('merge it? Yes, we can!', 'mg it?esw can!', 'ere Y, e')
# >>>, ('erge it? Yes, we can!', 'g it?esw can!', 'ere Y, e')
# >>>, ('rge it? Yes, we can!', 'g it?esw can!', 're Y, e')
# >>>, ('ge it? Yes, we can!', 'g it?esw can!', 'e Y, e')
# >>>, ('e it? Yes, we can!', ' it?esw can!', 'e Y, e')
# >>>, (' it? Yes, we can!', ' it?esw can!', ' Y, e')
# >>>, ('t?Yes, we can!', 't?esw can!', 'Y, e')
# >>>, ('?Yes, we can!', '?esw can!', 'Y, e')
# >>>, ('Yes, we can!', 'esw can!', 'Y, e')
# >>>, ('es, we can!', 'esw can!', ', e')
# >>>, ('s, we can!', 'sw can!', ', e')
# >>>, (', we can!', 'w can!', ', e')
# >>>, (' we can!', 'w can!', ' e')
# >>>, ('we can!', 'w can!', 'e')
# >>>, ('e can!', ' can!', 'e')
# >>>, (' can!', ' can!', '')
# Test Passed
# can handle some even more random cases
# >>>, (' ^#49Mj4qB', ' ^#9jB', '4M4q')
# >>>, ('^#49Mj4qB', '^#9jB', '4M4q')
# >>>, ('#49Mj4qB', '#9jB', '4M4q')
# >>>, ('49Mj4qB', '9jB', '4M4q')
# >>>, ('9Mj4qB', '9jB', 'M4q')
# >>>, ('Mj4qB', 'jB', 'M4q')
# >>>, ('j4qB', 'jB', '4q')
# >>>, ('4qB', 'B', '4q')
# >>>, ('qB', 'B', 'q')
# >>>, ('B', 'B', '')
# Test Passed
# >>>, ('xBrir)&oiE?K', 'xii', 'Brr)&oE?K')
# >>>, ('Brir)&oiE?K', 'ii', 'Brr)&oE?K')
# >>>, ('rir)&oiE?K', 'ii', 'rr)&oE?K')
# >>>, ('ir)&oiE?K', 'ii', 'r)&oE?K')
# >>>, ('r)&oiE?K', 'i', 'r)&oE?K')
# >>>, (')&oiE?K', 'i', ')&oE?K')
# >>>, ('&oiE?K', 'i', '&oE?K')
# >>>, ('oiE?K', 'i', 'oE?K')
# >>>, ('iE?K', 'i', 'E?K')
# >>>, ('E?K', '', 'E?K')
# Test Passed
# >>>, ('SGiOI][+5o\\]', 'iO+o\\', 'SGI][5]')
# >>>, ('GiOI][+5o\\]', 'iO+o\\', 'GI][5]')
# >>>, ('iOI][+5o\\]', 'iO+o\\', 'I][5]')
# >>>, ('OI][+5o\\]', 'O+o\\', 'I][5]')
# >>>, ('I][+5o\\]', '+o\\', 'I][5]')
# >>>, ('][+5o\\]', '+o\\', '][5]')
# >>>, ('[+5o\\]', '+o\\', '[5]')
# >>>, ('+5o\\]', '+o\\', '5]')
# >>>, ('5o\\]', 'o\\', '5]')
# >>>, ('o\\]', 'o\\', ']')
# >>>, ('\\]', '\\', ']')
# >>>, (']', '', ']')
# Test Passed
# >>>, ('b^eiXA!e9', '^eiXe9', 'bA!')
# >>>, ('^eiXA!e9', '^eiXe9', 'A!')
# >>>, ('eiXA!e9', 'eiXe9', 'A!')
# >>>, ('iXA!e9', 'iXe9', 'A!')
# >>>, ('XA!e9', 'Xe9', 'A!')
# >>>, ('A!e9', 'e9', 'A!')
# >>>, ('!e9', 'e9', '!')
# >>>, ('e9', 'e9', '')
# Test Passed
# >>>, (',%vPHPH"*mZ3>>>, ('%vPHPH"*mZ3>>>, ('vPHPH"*mZ3>>>, ('PHPH"*mZ3>>>, ('*mZ3>>>, ('mZ3>>>, ('Z3>>>, ('3>>>, ('>>>, ('YO', 'YO', '')
# Test Passed
# >>>, ('`s BJBO\\^J-', '`O\\^', 's BJBJ-')
# >>>, ('s BJBO\\^J-', 'O\\^', 's BJBJ-')
# >>>, (' BJBO\\^J-', 'O\\^', ' BJBJ-')
# >>>, ('BJBO\\^J-', 'O\\^', 'BJBJ-')
# >>>, ('JBO\\^J-', 'O\\^', 'JBJ-')
# >>>, ('BO\\^J-', 'O\\^', 'BJ-')
# >>>, ('O\\^J-', 'O\\^', 'J-')
# >>>, ('\\^J-', '\\^', 'J-')
# >>>, ('^J-', '^', 'J-')
# >>>, ('J-', '', 'J-')
# Test Passed
# >>>, ('j:iQ1+I)e', 'j:1)', 'iQ+Ie')
# >>>, (':iQ1+I)e', ':1)', 'iQ+Ie')
# >>>, ('iQ1+I)e', '1)', 'iQ+Ie')
# >>>, ('Q1+I)e', '1)', 'Q+Ie')
# >>>, ('1+I)e', '1)', '+Ie')
# >>>, ('+I)e', ')', '+Ie')
# >>>, ('I)e', ')', 'Ie')
# >>>, (')e', ')', 'e')
# >>>, ('e', '', 'e')
# Test Passed
# >>>, ("jN/6z'F%N;d:", 'N6z%d:', "j/'FN;")
# >>>, ("N/6z'F%N;d:", 'N6z%d:', "/'FN;")
# >>>, ("/6z'F%N;d:", '6z%d:', "/'FN;")
# >>>, ("6z'F%N;d:", '6z%d:', "'FN;")
# >>>, ("z'F%N;d:", 'z%d:', "'FN;")
# >>>, ("'F%N;d:", '%d:', "'FN;")
# >>>, ('F%N;d:', '%d:', 'FN;')
# >>>, ('%N;d:', '%d:', 'N;')
# >>>, ('N;d:', 'd:', 'N;')
# >>>, (';d:', 'd:', ';')
# >>>, ('d:', 'd:', '')
# Test Passed
# >>>, ('VlqMA^Yog5Gh6D', 'VlA^Y6D', 'qMog5Gh')
# >>>, ('lqMA^Yog5Gh6D', 'lA^Y6D', 'qMog5Gh')
# >>>, ('qMA^Yog5Gh6D', 'A^Y6D', 'qMog5Gh')
# >>>, ('MA^Yog5Gh6D', 'A^Y6D', 'Mog5Gh')
# >>>, ('A^Yog5Gh6D', 'A^Y6D', 'og5Gh')
# >>>, ('^Yog5Gh6D', '^Y6D', 'og5Gh')
# >>>, ('Yog5Gh6D', 'Y6D', 'og5Gh')
# >>>, ('og5Gh6D', '6D', 'og5Gh')
# >>>, ('g5Gh6D', '6D', 'g5Gh')
# >>>, ('5Gh6D', '6D', '5Gh')
# >>>, ('Gh6D', '6D', 'Gh')
# >>>, ('h6D', '6D', 'h')
# >>>, ('6D', '6D', '')
# Test Passed
# >>>, ("Mb&c'PP;qyJLY2j9A\\I", 'Mc;qy\\', "b&'PPJLY2j9AI")
# >>>, ("b&c'PP;qyJLY2j9A\\I", 'c;qy\\', "b&'PPJLY2j9AI")
# >>>, ("&c'PP;qyJLY2j9A\\I", 'c;qy\\', "&'PPJLY2j9AI")
# >>>, ("c'PP;qyJLY2j9A\\I", 'c;qy\\', "'PPJLY2j9AI")
# >>>, ("'PP;qyJLY2j9A\\I", ';qy\\', "'PPJLY2j9AI")
# >>>, ('PP;qyJLY2j9A\\I', ';qy\\', 'PPJLY2j9AI')
# >>>, ('P;qyJLY2j9A\\I', ';qy\\', 'PJLY2j9AI')
# >>>, (';qyJLY2j9A\\I', ';qy\\', 'JLY2j9AI')
# >>>, ('qyJLY2j9A\\I', 'qy\\', 'JLY2j9AI')
# >>>, ('yJLY2j9A\\I', 'y\\', 'JLY2j9AI')
# >>>, ('JLY2j9A\\I', '\\', 'JLY2j9AI')
# >>>, ('LY2j9A\\I', '\\', 'LY2j9AI')
# >>>, ('Y2j9A\\I', '\\', 'Y2j9AI')
# >>>, ('2j9A\\I', '\\', '2j9AI')
# >>>, ('j9A\\I', '\\', 'j9AI')
# >>>, ('9A\\I', '\\', '9AI')
# >>>, ('A\\I', '\\', 'AI')
# >>>, ('\\I', '\\', 'I')
# >>>, ('I', '', 'I')
# Test Passed
# >>>, ('Ri^ >kcrC/rH-.!He', 'ikcCrH-.!He', 'R^ >r/')
# >>>, ('i^ >kcrC/rH-.!He', 'ikcCrH-.!He', '^ >r/')
# >>>, ('^ >kcrC/rH-.!He', 'kcCrH-.!He', '^ >r/')
# >>>, (' >kcrC/rH-.!He', 'kcCrH-.!He', ' >r/')
# >>>, ('>kcrC/rH-.!He', 'kcCrH-.!He', '>r/')
# >>>, ('kcrC/rH-.!He', 'kcCrH-.!He', 'r/')
# >>>, ('crC/rH-.!He', 'cCrH-.!He', 'r/')
# >>>, ('rC/rH-.!He', 'CrH-.!He', 'r/')
# >>>, ('C/rH-.!He', 'CrH-.!He', '/')
# >>>, ('/rH-.!He', 'rH-.!He', '/')
# >>>, ('rH-.!He', 'rH-.!He', '')
# Test Passed
# >>>, ('Rio4/0]*0,OB>Oq', 'R4/0]*0,q', 'ioOB>O')
# >>>, ('io4/0]*0,OB>Oq', '4/0]*0,q', 'ioOB>O')
# >>>, ('o4/0]*0,OB>Oq', '4/0]*0,q', 'oOB>O')
# >>>, ('4/0]*0,OB>Oq', '4/0]*0,q', 'OB>O')
# >>>, ('/0]*0,OB>Oq', '/0]*0,q', 'OB>O')
# >>>, ('0]*0,OB>Oq', '0]*0,q', 'OB>O')
# >>>, (']*0,OB>Oq', ']*0,q', 'OB>O')
# >>>, ('*0,OB>Oq', '*0,q', 'OB>O')
# >>>, ('0,OB>Oq', '0,q', 'OB>O')
# >>>, (',OB>Oq', ',q', 'OB>O')
# >>>, ('OB>Oq', 'q', 'OB>O')
# >>>, ('B>Oq', 'q', 'B>O')
# >>>, ('>Oq', 'q', '>O')
# >>>, ('Oq', 'q', 'O')
# >>>, ('q', 'q', '')
# Test Passed
# >>>, (' @jV$JeN4x(JW', '@jJN4x(J', ' V$eW')
# >>>, ('@jV$JeN4x(JW', '@jJN4x(J', 'V$eW')
# >>>, ('jV$JeN4x(JW', 'jJN4x(J', 'V$eW')
# >>>, ('V$JeN4x(JW', 'JN4x(J', 'V$eW')
# >>>, ('$JeN4x(JW', 'JN4x(J', '$eW')
# >>>, ('JeN4x(JW', 'JN4x(J', 'eW')
# >>>, ('eN4x(JW', 'N4x(J', 'eW')
# >>>, ('N4x(JW', 'N4x(J', 'W')
# >>>, ('4x(JW', '4x(J', 'W')
# >>>, ('x(JW', 'x(J', 'W')
# >>>, ('(JW', '(J', 'W')
# >>>, ('JW', 'J', 'W')
# >>>, ('W', '', 'W')
# Test Passed
# >>>, ("'e;Q)x[!,$m%iN?(rR", ';Q[,mNR', "'e)x!$%i?(r")
# >>>, ('e;Q)x[!,$m%iN?(rR', ';Q[,mNR', 'e)x!$%i?(r')
# >>>, (';Q)x[!,$m%iN?(rR', ';Q[,mNR', ')x!$%i?(r')
# >>>, ('Q)x[!,$m%iN?(rR', 'Q[,mNR', ')x!$%i?(r')
# >>>, (')x[!,$m%iN?(rR', '[,mNR', ')x!$%i?(r')
# >>>, ('x[!,$m%iN?(rR', '[,mNR', 'x!$%i?(r')
# >>>, ('[!,$m%iN?(rR', '[,mNR', '!$%i?(r')
# >>>, ('!,$m%iN?(rR', ',mNR', '!$%i?(r')
# >>>, (',$m%iN?(rR', ',mNR', '$%i?(r')
# >>>, ('$m%iN?(rR', 'mNR', '$%i?(r')
# >>>, ('m%iN?(rR', 'mNR', '%i?(r')
# >>>, ('%iN?(rR', 'NR', '%i?(r')
# >>>, ('iN?(rR', 'NR', 'i?(r')
# >>>, ('N?(rR', 'NR', '?(r')
# >>>, ('?(rR', 'R', '?(r')
# >>>, ('(rR', 'R', '(r')
# >>>, ('rR', 'R', 'r')
# >>>, ('R', 'R', '')
# Test Passed
# >>>, ('Ka7wi=KXpug,p', '7ip', 'Kaw=KXug,p')
# >>>, ('a7wi=KXpug,p', '7ip', 'aw=KXug,p')
# >>>, ('7wi=KXpug,p', '7ip', 'w=KXug,p')
# >>>, ('wi=KXpug,p', 'ip', 'w=KXug,p')
# >>>, ('i=KXpug,p', 'ip', '=KXug,p')
# >>>, ('=KXpug,p', 'p', '=KXug,p')
# >>>, ('KXpug,p', 'p', 'KXug,p')
# >>>, ('Xpug,p', 'p', 'Xug,p')
# >>>, ('pug,p', 'p', 'ug,p')
# >>>, ('ug,p', '', 'ug,p')
# Test Passed
# >>>, (']M%-ry9i1R', ']y91R', 'M%-ri')
# >>>, ('M%-ry9i1R', 'y91R', 'M%-ri')
# >>>, ('%-ry9i1R', 'y91R', '%-ri')
# >>>, ('-ry9i1R', 'y91R', '-ri')
# >>>, ('ry9i1R', 'y91R', 'ri')
# >>>, ('y9i1R', 'y91R', 'i')
# >>>, ('9i1R', '91R', 'i')
# >>>, ('i1R', '1R', 'i')
# >>>, ('1R', '1R', '')
# Test Passed
# >>>, ('Qhnc3;e%V[2To', 'QV[o', 'hnc3;e%2T')
# >>>, ('hnc3;e%V[2To', 'V[o', 'hnc3;e%2T')
# >>>, ('nc3;e%V[2To', 'V[o', 'nc3;e%2T')
# >>>, ('c3;e%V[2To', 'V[o', 'c3;e%2T')
# >>>, ('3;e%V[2To', 'V[o', '3;e%2T')
# >>>, (';e%V[2To', 'V[o', ';e%2T')
# >>>, ('e%V[2To', 'V[o', 'e%2T')
# >>>, ('%V[2To', 'V[o', '%2T')
# >>>, ('V[2To', 'V[o', '2T')
# >>>, ('[2To', '[o', '2T')
# >>>, ('2To', 'o', '2T')
# >>>, ('To', 'o', 'T')
# >>>, ('o', 'o', '')
# Test Passed
# >>>, ('ek,IpCE3>>>, ('k,IpCE3>>>, (',IpCE3>>>, ('IpCE3>>>, ('pCE3>>>, ('CE3>>>, ('E3>>>, ('3>>>, ('
# Test Passed
# >>>, ('q8-n^Z(aZt!=+r(nYjH', '^aZY', 'q8-nZ(t!=+r(njH')
# >>>, ('8-n^Z(aZt!=+r(nYjH', '^aZY', '8-nZ(t!=+r(njH')
# >>>, ('-n^Z(aZt!=+r(nYjH', '^aZY', '-nZ(t!=+r(njH')
# >>>, ('n^Z(aZt!=+r(nYjH', '^aZY', 'nZ(t!=+r(njH')
# >>>, ('^Z(aZt!=+r(nYjH', '^aZY', 'Z(t!=+r(njH')
# >>>, ('Z(aZt!=+r(nYjH', 'aZY', 'Z(t!=+r(njH')
# >>>, ('(aZt!=+r(nYjH', 'aZY', '(t!=+r(njH')
# >>>, ('aZt!=+r(nYjH', 'aZY', 't!=+r(njH')
# >>>, ('Zt!=+r(nYjH', 'ZY', 't!=+r(njH')
# >>>, ('t!=+r(nYjH', 'Y', 't!=+r(njH')
# >>>, ('!=+r(nYjH', 'Y', '!=+r(njH')
# >>>, ('=+r(nYjH', 'Y', '=+r(njH')
# >>>, ('+r(nYjH', 'Y', '+r(njH')
# >>>, ('r(nYjH', 'Y', 'r(njH')
# >>>, ('(nYjH', 'Y', '(njH')
# >>>, ('nYjH', 'Y', 'njH')
# >>>, ('YjH', 'Y', 'jH')
# >>>, ('jH', '', 'jH')
# Test Passed
# >>>, ("kF+bf<'s@])]HUO%", '>>>, ("F+bf<'s@])]HUO%", '>>>, ("+bf<'s@])]HUO%", '>>>, ("bf<'s@])]HUO%", '>>>, ("f<'s@])]HUO%", '>>>, ("<'s@])]HUO%", '>>>, ("'s@])]HUO%", 's@])]O', "'HU%")
# >>>, ('s@])]HUO%', 's@])]O', 'HU%')
# >>>, ('@])]HUO%', '@])]O', 'HU%')
# >>>, ('])]HUO%', '])]O', 'HU%')
# >>>, (')]HUO%', ')]O', 'HU%')
# >>>, (']HUO%', ']O', 'HU%')
# >>>, ('HUO%', 'O', 'HU%')
# >>>, ('UO%', 'O', 'U%')
# >>>, ('O%', 'O', '%')
# >>>, ('%', '', '%')
# Test Passed
# 55 Passed
# 1 Failed
# 0 Errors
# Process took 91ms to complete